
import sys

with open('main.py', 'r', encoding='utf-8') as f:
    lines = f.readlines()

# Localizar la función report_oee_day
start_line = -1
for i, line in enumerate(lines):
    if '@app.post("/api/report/oee/day/")' in line:
        start_line = i
        break

if start_line == -1:
    print("No se encontró el endpoint /api/report/oee/day/")
    sys.exit(1)

# Encontrar el final de la función (el siguiente endpoint o el final del archivo)
end_line = -1
for i in range(start_line + 1, len(lines)):
    if '@app.post(' in lines[i] or '@app.get(' in lines[i]:
        end_line = i
        break

if end_line == -1:
    end_line = len(lines)

new_func = [
    '@app.post("/api/report/oee/day/")\n',
    'async def report_oee_day(payload: dict):\n',
    '    """Descarga el análisis (PDF/Word) para OEE por día/rango/turno."""\n',
    '    from_day = normalize_day_str(payload.get("from_day") or payload.get("day") or "")\n',
    '    to_day = normalize_day_str(payload.get("to_day") or from_day)\n',
    '    shift_name = payload.get("shift_name")\n',
    '    fmt = (payload.get("format") or "pdf").lower()\n',
    '    provided_rows = payload.get("rows")\n',
    '    provided_cols = payload.get("columns")\n',
    '    provided_ai = payload.get("ai_analysis")\n',
    '    provided_stops = payload.get("stop_reasons")\n',
    '\n',
    '    if not re.match(r"^\\d{4}-\\d{2}-\\d{2}$", from_day):\n',
    '        raise HTTPException(status_code=400, detail=f"Formato de \'from_day\' inválido ({from_day}). Usa YYYY-MM-DD.")\n',
    '\n',
    '    if provided_rows and provided_cols:\n',
    '        rows = provided_rows\n',
    '        cols = provided_cols\n',
    '    else:\n',
    '        api_payload = {"from_day": from_day, "to_day": to_day}\n',
    '        if shift_name and str(shift_name).strip() and shift_name not in ("(Todos)", "(todos)", "todos", "(all)", "(All)"):\n',
    '            api_payload["shift_name"] = shift_name\n',
    '\n',
    '        try:\n',
    '            api_payload["skip_ai"] = True\n',
    '            data = await api_oee_day_turn(api_payload)\n',
    '            cols = data.get("columns") or []\n',
    '            rows = data.get("rows") or []\n',
    '            raw_daily = data.get("raw_daily") or []\n',
    '            summary_obj = data.get("summary") or {}\n',
    '            if not provided_ai:\n',
    '                provided_ai = data.get("ai_analysis")\n',
    '        except HTTPException as he:\n',
    '            raise he\n',
    '        except Exception as e:\n',
    '            print(f"Error reporte OEE Day: {e}")\n',
    '            raise HTTPException(status_code=500, detail=f"Error interno: {str(e)}")\n',
    '\n',
    '    if not cols or not rows:\n',
    '        raise HTTPException(status_code=404, detail="No hay datos para esa fecha/rango.")\n',
    '\n',
    '    table_rows = []\n',
    '    for r in rows:\n',
    '        r_list = list(r) if isinstance(r, (tuple, list)) else [r]\n',
    '        row_dict = {c: (r_list[i] if i < len(r_list) else "") for i, c in enumerate(cols)}\n',
    '        table_rows.append(row_dict)\n',
    '\n',
    '    period_label = from_day if from_day == to_day else f"{from_day} a {to_day}"\n',
    '    title = "Reporte Ejecutivo de Inteligencia Operacional — Duma"\n',
    '    subtitle = f"Periodo: {period_label}" + (f" — Turno: {shift_name}" if shift_name else "")\n',
    '\n',
    '    ai_text = provided_ai or ""\n',
    '\n',
    '    image_paths = []\n',
    '    provided_images = payload.get("images") or []\n',
    '\n',
    '    if provided_images:\n',
    '        import base64, uuid, os\n',
    '        for b64 in provided_images:\n',
    '            if b64.startswith("data:image/png;base64,"):\n',
    '                try:\n',
    '                    img_data = base64.b64decode(b64.split(",")[1])\n',
    '                    tmp_path = os.path.join(PLOTS_DIR, f"tmp_oee_hist_{uuid.uuid4().hex[:8]}.png")\n',
    '                    with open(tmp_path, "wb") as bf:\n',
    '                        bf.write(img_data)\n',
    '                    image_paths.append(tmp_path)\n',
    '                except Exception as e:\n',
    '                    print(f"Error decodificando imagen dashboard HIST: {e}")\n',
    '\n',
    '    if not image_paths:\n',
    '        try:\n',
    '            api_payload = {"from_day": from_day, "to_day": to_day, "skip_ai": True}\n',
    '            if shift_name and str(shift_name).strip() and shift_name not in ("(Todos)", "(todos)", "todos", "(all)", "(All)"):\n',
    '                api_payload["shift_name"] = shift_name\n',
    '            \n',
    '            hist_data = await api_oee_day_turn(api_payload)\n',
    '            rd = hist_data.get("raw_daily") or []\n',
    '            summary_obj = hist_data.get("summary") or {}\n',
    '            if rd:\n',
    '                image_paths.extend(_generate_hist_pdf_plt(rd))\n',
    '            \n',
    '            if provided_stops:\n',
    '                image_paths.extend(_generate_pareto_pdf_plt(provided_stops, period_label))\n',
    '        except Exception as e:\n',
    '            print(f"Error Graficando Histrico Nativo: {e}")\n',
    '\n',
    '    sections = []\n',
    '    # Capturas visuales del dashboard - sin texto redundante\n',
    '    \n',
    '    if image_paths:\n',
    '        evol_imgs = [img for img in image_paths if "hist_oee" in img or "hist_prod" in img or "hist_np" in img or "hist_cnt" in img]\n',
    '        pareto_imgs = [img for img in image_paths if "pareto" in img or "treemap" in img]\n',
    '        other_imgs = [img for img in image_paths if img not in evol_imgs and img not in pareto_imgs]\n',
    '\n',
    '        if evol_imgs:\n',
    '            sections.append({\n',
    '                "title": "Evolución de Desempeño y Producción",\n',
    '                "text": "Seguimiento diario de OEE y cumplimiento de producción.",\n',
    '                "images": evol_imgs[:2]\n',
    '            })\n',
    '            sections.append({\n',
    '                "title": "Análisis de Disponibilidad y Paros",\n',
    '                "text": "Duración y frecuencia de eventos de paro (P/NP).",\n',
    '                "images": evol_imgs[2:]\n',
    '            })\n',
    '        \n',
    '        if pareto_imgs:\n',
    '            sections.append({\n',
    '                "title": "Diagnóstico Raíz (Pareto 80/20)",\n',
    '                "text": "Principales causas de pérdida de disponibilidad.",\n',
    '                "images": pareto_imgs\n',
    '            })\n',
    '        \n',
    '        if other_imgs:\n',
    '            sections.append({\n',
    '                "title": "Análisis Visual Adicional",\n',
    '                "text": "Otras métricas operativas detectadas.",\n',
    '                "images": other_imgs\n',
    '            })\n',
    '\n',
    '    if ai_text.strip():\n',
    '        sections.append({"title": "Diagnóstico y Recomendaciones (Duma AI)", "text": ai_text})\n',
    '\n',
    '    fmt = (fmt or "pdf").lower()\n',
    '    rep_slug = f"oee_{from_day}" if from_day == to_day else f"oee_{from_day}_to_{to_day}"\n',
    '    if fmt in ("docx", "word"):\n',
    '        content = _build_docx_bytes(title, subtitle, sections, "Resultado", table_rows, logo_path=_LOGO_PATH)\n',
    '        return _as_file_response(\n',
    '            content,\n',
    '            _report_filename(rep_slug + (f"_{shift_name}" if shift_name else ""), "docx"),\n',
    '            "application/vnd.openxmlformats-officedocument.wordprocessingml.document",\n',
    '        )\n',
    '\n',
    '    _kpis = []\n',
    '    try:\n',
    '        if \'summary_obj\' in locals() and summary_obj:\n',
    '            def _f(v): return float(v) if v is not None else 0.0\n',
    '            _kpis = [\n',
    '                {"label": "OEE Consolidado",   "value": f"{_f(summary_obj.get(\'OEE\')):.1f}%",           "status": "Eficiencia del rango"},\n',
    '                {"label": "Disponibilidad",     "value": f"{_f(summary_obj.get(\'Availability\')):.1f}%",  "status": "Uso del tiempo"},\n',
    '                {"label": "Desempeño",          "value": f"{_f(summary_obj.get(\'Performance\')):.1f}%",   "status": "Ritmo de producción"},\n',
    '                {"label": "Calidad",            "value": f"{_f(summary_obj.get(\'Quality\')):.1f}%",       "status": "Producto conforme"},\n',
    '            ]\n',
    '        else:\n',
    '            _ov = [float(r.get("OEE") or 0) for r in table_rows if r.get("OEE") is not None]\n',
    '            _pv = [float(r.get("CurrentProduction") or r.get("CurrentShiftProduction") or 0) for r in table_rows]\n',
    '            _np = [float(r.get("TiempoNoProdNoProgramadoMin") or 0) for r in table_rows]\n',
    '            if _ov:  _kpis.append({"label": "OEE Promedio",     "value": f"{sum(_ov)/len(_ov):.1f}%",  "status": "Eficiencia del periodo"})\n',
    '            if _pv:  _kpis.append({"label": "Produccion Total", "value": f"{sum(_pv):,.0f} Kg",       "status": f"Turnos: {len(table_rows)}"})\n',
    '            if _np:  _kpis.append({"label": "Paros No Prog.",   "value": f"{sum(_np):,.0f} min",      "status": "Tiempo total perdido"})\n',
    '    except Exception as e: \n',
    '        print(f"Error extrae KPIs HIST: {e}")\n',
    '        _kpis = []\n',
    '\n',
    '    import base64, uuid\n',
    '    snap_dir = os.path.join("static", "temp_snaps")\n',
    '    os.makedirs(snap_dir, exist_ok=True)\n',
    '\n',
    '    kpi_snap_path = None\n',
    '    kpi_snapshot_b64 = payload.get("kpi_snapshot")\n',
    '    if kpi_snapshot_b64 and "," in kpi_snapshot_b64:\n',
    '        try:\n',
    '            data = base64.b64decode(kpi_snapshot_b64.split(",", 1)[1])\n',
    '            kpi_snap_path = os.path.join(snap_dir, f"oee_kpi_snap_{uuid.uuid4().hex[:8]}.png")\n',
    '            with open(kpi_snap_path, "wb") as f: f.write(data)\n',
    '        except Exception as e: print(f"Error oee kpi_snap: {e}")\n',
    '\n',
    '    table_snap_path = None\n',
    '    table_snapshot_b64 = payload.get("table_snapshot")\n',
    '    if table_snapshot_b64 and "," in table_snapshot_b64:\n',
    '        try:\n',
    '            data = base64.b64decode(table_snapshot_b64.split(",", 1)[1])\n',
    '            table_snap_path = os.path.join(snap_dir, f"oee_table_snap_{uuid.uuid4().hex[:8]}.png")\n',
    '            with open(table_snap_path, "wb") as f: f.write(data)\n',
    '        except Exception as e: print(f"Error oee table_snap: {e}")\n',
    '\n',
    '    content = _build_pdf_bytes(title, subtitle, sections, "Resultado", table_rows, logo_path=_LOGO_PATH, kpi_cards=_kpis, kpi_snapshot_path=kpi_snap_path, table_snapshot_path=table_snap_path)\n',
    '    return _as_file_response(\n',
    '        content,\n',
    '        _report_filename(rep_slug + (f"_{shift_name}" if shift_name else ""), "pdf"),\n',
    '        "application/pdf",\n',
    '    )\n'
]

# Reemplazar la función
lines[start_line:end_line] = new_func

with open('main.py', 'w', encoding='utf-8') as f:
    f.writelines(lines)

print("Función report_oee_day restaurada y corregida.")
